# Generated by Django 5.0.6 on 2024-06-18 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="age",
        ),
    ]
